### PR TITLE
Support full filenames in logs.

### PR DESCRIPTION
**Pull request by spinorx**

### CODE REVIEW

**Comment by KjellKod** [comment]
@spinorx thanks for the pull request. 

Please provide the following
1. Addition to the `Options` cmake file. Please make the default for this define as false. 
2. A description for the pull request. For historical reasons a one or two liners - however obvious makes it easier for people when browsing changes. 

Cheers
Kjell

**Comment by spinorx** [comment]
Updated.  Let me know.  Also fixed 2 macros which didn't have parentheses around them.

**Comment by KjellKod** [comment]
:+1:

**Comment by KjellKod** [comment]
Thanks for the contribution

**Pull request merged**
