### PR TITLE
Handle case when directory lacks a terminating path separator

### PR DESCRIPTION
**Pull request by maj-tom**
This was already working in the ctor.

### CODE REVIEW

**Comment by KjellKod** [comment]
Thanks. It looks like a good change.

Please look at the failing unit tests and address the failures

https://ci.appveyor.com/project/KjellKod/g3log/build/1.0.81

**Comment by KjellKod** [comment]
@maj-tom please address the failing unit tests. This is needed for the PR to go any further.

**Comment by maj-tom** [comment]
Hey, how the heck do I run these unit tests in Visual C++? I see the source files and Cmake script, but nothing in the solution file.

**Comment by KjellKod** [comment]
You can always compile it on the command line. The CMake files should have pointers in that regard

**Comment by KjellKod** [comment]
You can also check the Travis file

**Comment by maj-tom** [comment]
Hi, I'm having some trouble understanding the test in question.
Building current master, I added a breakpoint in test_filechange.cpp line 81 (`auto old_log = getLogName();`). The resulting value there is `some_fake_DirectoryOrName_1_)1_(ReplaceLogFile).g3log.20171113-185031.log(ReplaceLogFile).g3log.20171113-185031.log"`
Looks like it appended it twice. Again, this is the current master, not any change I made to the code. Can you clarify?

**Comment by KjellKod** [comment]
Not sure what the confusion is. "GetLogName" returns the current logname. Read the code. Read the tests. It's not complex code

**Comment by maj-tom** [comment]
My confusion is not that the name is long, but that its of the form A+A where A = (some_fake_DirectoryOrName_1_)1_(ReplaceLogFile).g3log.20171113-185031.log and + is string concatenation. Why is it duplicated?

**Pull request closed without merging**
