### PR TITLE
iOS Support (#183)

### PR DESCRIPTION
**Pull request by mobileben**
These are the changes that should build for iOS. I wasn't sure about how to properly integrate into the overall cmake build. I ended up winging it a bit, but things should be able to be easily moved around.

### CODE REVIEW

**Comment by KjellKod** [comment]
@mobileben do you have any experience with IOS Cloud-CI integration in github? 
Here's an example: https://github.com/integrations/circle-ci
and here's some more: https://circleci.com/mobile/

The reason I'm bringing it up is that this is adding another platform to the suite of platforms. I currently have no experience developing for IOS and it is costly (especially in terms of time) to set up an IOS development platform to test g3log. 

I'm happy to add the circle-ci integration if you can add the necessary setup for this in this pull request.

**Comment by mobileben** [comment]
Kjell,

Totally understand. It’s not worth setting any of the stuff up for iOS unless you really need to.

Yeah, no problem. Let me take a look at it this weekend. I haven’t used that particular service, but I have done Jenkins Ci for some of the iOS projects I’ve worked on.

I can get it working in my branch first. I may have some questions around unit tests to run. While there is a “main()”, it doesn’t quite work the way it would for a console type app.

Ben

**Comment by mobileben** [comment]
BTW, I still have this on my radar. I'm in the middle of integrating some client code with the newer server code. Once I get clear of that, I plan on looking into the circle-CI.

**Comment by mobileben** [comment]
BTW, I still have this on my radar. I'm in the middle of integrating some client code with the newer server code. Once I get clear of that, I plan on looking into the circle-CI.

**Comment by KjellKod** [comment]
@mobileben review wise this looks good.  If we can get some CI for it then it's good to be merged. Till then (or until it is community verified) let's leave the PR up.  Thanks

**Comment by mobileben** [comment]
I hope to get on this soon. Been unfortunately tied up a bit more on work stuff

**Comment by KjellKod** [comment]
@mobileben have you had any time to look at this?  It doesn't change existing functionality so I have no problem merging this,. it's just annoying if it would break without CI feedback.

**Comment by mobileben** [comment]
@KjellKod my apologies for the delay, I've been super swamped with stuff. Let me take a gander at this over the weekend.

**Comment by KjellKod** [comment]
Awesome. No worries . It seems like good stuff so I'm excited if we can get it in

**Comment by mobileben** [comment]
It'd be great to allow others to use it. I've been using it daily, however, that only really means that it happens to work with how my code is using it. There are no doubt many other ways to stress it.

Regarding unit tests, which ones should I be looking to recreate (all?). I'm asking because depending on how Cloud-CI works, it may need to run in a simulator. So I need to figure out how to make them play well together (it's possible it's just plug and play, I haven't looked into this yet).

**Comment by KjellKod** [comment]
I would go for all that are enabled by default

**Comment by mobileben** [comment]
As an FYI, I have a prelim test (non-g3log) related running on CircleCI and Travis. It turns out CircleCI will activate OSS projects for free if you ask. I'm doing this on weekends for an hour or so, so hopefully in the next weekend or two it will be up and running. I will have some questions because there will be some oddness as this has to get pushed into an Xcode project.

**Comment by KjellKod** [comment]
Sweet! Nice work

* Contact Information
* Kjell Hedström
* Mobile:  +1 - 617.378.1915
* E-mail: Hedstrom@KjellKod.cc

**Comment by KjellKod** [comment]
:+1:  it is beta still. If we can get CI to work for it it would be amazing. Till then I will approve it for the benefit of the community. although it might not be in CI driven environment at the moment

**Pull request merged**
