### PR TITLE
Addressing the std2 concern raised in issue 212

### PR DESCRIPTION
**Pull request by KjellKod**
Addressing issue: https://github.com/KjellKod/g3log/issues/212

### CODE REVIEW

**Comment by cstamatopoulos** [comment]
In g3sinks, LogRotateWithFilter.cpp there is 1 call to std2 as well. 
Do you want a pull request or you are ok sorting out?

**Comment by KjellKod** [comment]
Ah, shoot! 

Thanks. I’ll adress that today

**Comment by KjellKod** [comment]
It should be corrected now

**Comment by cstamatopoulos** [comment]
Thanks.

**Pull request merged**
