### PR TITLE
Fix ARM compilation for windows.

### PR DESCRIPTION
**Pull request by englercj**
Added support for ARM in the windows stacktrace utility.

### CODE REVIEW

**Comment by KjellKod** [comment]
Ideally this would be covered by one of the cloud CIs. I don’t see that as feasible so I’ll approve and merge it. 

Please think about it, if it’s available with ARM on any of the 3 cloud CI we are using them adding ARM support for it would help to future proof ARM support

**Review by KjellKod — APPROVED** [review]

**Comment by KjellKod** [comment]
I’m holding off with merging until you you give me the OK that you are confident it’ll work for ARM. 

I’ve no way of verifying this apart from code reviewing

**Comment by englercj** [comment]
Unfortunately I too don't have a machine to verify on, yet. Also unfortunate is the complexity of windows ARM where you generally build on x86 and deploy to ARM.

I've seen similar changes to other stack trace handling code that was updated for ARM though so I'm fairly confident this is correct. I'm also fine leaving it open until we have a chance to verify, but it may be some time for me before I get there. I'm building for ARM64 windows currently, but not ready for testing yet.

**Comment by englercj** [comment]
I think AppVeyor has ARM64 support (from googling) but I'm not familiar enough with that platform you get it running.

**Comment by KjellKod** [comment]
I'm going out on a limb here and making it available. Please consider adding CI support for this later

**Pull request merged**
