### PR TITLE
compiles on arm

### PR DESCRIPTION
**Pull request by AndreasSchoenle**
Seems to be necessary to compile on my arm platform. gcc 4.7.2 complains without it.

### CODE REVIEW

**Comment by KjellKod** [comment]
Do you have the option of upgrading compiler?  gcc 4.7.2 had really weak C++11 support.

**Comment by AndreasSchoenle** [comment]
Unfortunately not. I have not control over the toolchain which includes custom built standard libraries. This is the only thing it complained about, though, and the library runs fine when compiled with this patch.

**Comment by KjellKod** [comment]
Can you please give me the error message. What happens when this change is not in?

**Comment by AndreasSchoenle** [comment]
Below is the output of the compiler (I have clipped the paths to the sysroot, I cross-compile on windows). Sorry for the unreadable format here but Cut and Paste to e.g. notepad++ makes it readable again. But I have narrowed down the problem: gcc 4.7 thinks it has to instantiate a SinkWrapper object because of the constructor of Sink:

```
   template<typename DefaultLogCall >
         Sink(std::unique_ptr<T> sink, DefaultLogCall call)
            : SinkWrapper {},
         _real_sink {std::move(sink)},
         _bg(kjellkod::Active::createActive()),
         _default_log_call(std::bind(call, _real_sink.get(), std::placeholders::_1)) {
         }
```
Changing this to 

```
template<typename DefaultLogCall >
         Sink(std::unique_ptr<T> sink, DefaultLogCall call) :
         _real_sink {std::move(sink)},
         _bg(kjellkod::Active::createActive()),
         _default_log_call(std::bind(call, _real_sink.get(), std::placeholders::_1)) {
         }
```

Solves the problem, too. Let me know if this is preferable and I can do another merge request with this change. I believe it will not change much in the compiled code.

Best,
Andreas

> In file included from E:\Sources\Packages\g3log-1.2\g3log\src/g3log/sinkhandle.hpp:11:0,
                 from E:\Sources\Packages\g3log-1.2\g3log\src\g3log/logworker.hpp:16,
                 from E:\Sources\Packages\g3log-1.2\g3log\src\logworker.cpp:9:
E:\Sources\Packages\g3log-1.2\g3log\src/g3log/sink.hpp: In instantiation of 'g3::internal::Sink<T>::Sink(std::unique_ptr<T>, DefaultLogCall) [with DefaultLogCall = void (g3::FileSink::*)(g3::MoveOnCopy<g3::LogMessage>); T = g3::FileSink]':
/usr/include/c++/4.7.2/ext/new_allocator.h:110:4:   required from 'void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = g3::internal::Sink<g3::FileSink>; _Args = {std::unique_ptr<g3::FileSink, std::default_delete<g3::FileSink> >, void (g3::FileSink::*&)(g3::MoveOnCopy<g3::LogMessage>)}; _Tp = g3::internal::Sink<g3::FileSink>]'
/usr/include/c++/4.7.2/bits/alloc_traits.h:253:4:   required from 'static typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type std::allocator_traits<_Alloc>::_S_construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = g3::internal::Sink<g3::FileSink>; _Args = {std::unique_ptr<g3::FileSink, std::default_delete<g3::FileSink> >, void (g3::FileSink::*&)(g3::MoveOnCopy<g3::LogMessage>)}; _Alloc = std::allocator<g3::internal::Sink<g3::FileSink> >; typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type = void]'
/usr/include/c++/4.7.2/bits/alloc_traits.h:390:4:   required from 'static void std::allocator_traits<_Alloc>::construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = g3::internal::Sink<g3::FileSink>; _Args = {std::unique_ptr<g3::FileSink, std::default_delete<g3::FileSink> >, void (g3::FileSink::*&)(g3::MoveOnCopy<g3::LogMessage>)}; _Alloc = std::allocator<g3::internal::Sink<g3::FileSink> >]'
/usr/include/c++/4.7.2/bits/shared_ptr_base.h:402:4:   required from 'std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_Sp_counted_ptr_inplace(_Alloc, _Args&& ...) [with _Args = {std::unique_ptr<g3::FileSink, std::default_delete<g3::FileSink> >, void (g3::FileSink::*&)(g3::MoveOnCopy<g3::LogMessage>)}; _Tp = g3::internal::Sink<g3::FileSink>; _Alloc = std::allocator<g3::internal::Sink<g3::FileSink> >; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]'
/usr/include/c++/4.7.2/ext/new_allocator.h:110:4:   required from 'void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = std::_Sp_counted_ptr_inplace<g3::internal::Sink<g3::FileSink>, std::allocator<g3::internal::Sink<g3::FileSink> >, (__gnu_cxx::_Lock_policy)2u>; _Args = {const std::allocator<g3::internal::Sink<g3::FileSink> >, std::unique_ptr<g3::FileSink, std::default_delete<g3::FileSink> >, void (g3::FileSink::*&)(g3::MoveOnCopy<g3::LogMessage>)}; _Tp = std::_Sp_counted_ptr_inplace<g3::internal::Sink<g3::FileSink>, std::allocator<g3::internal::Sink<g3::FileSink> >, (__gnu_cxx::_Lock_policy)2u>]'
/usr/include/c++/4.7.2/bits/alloc_traits.h:253:4:   [ skipping 3 instantiation contexts ]
/usr/include/c++/4.7.2/bits/shared_ptr_base.h:997:35:   required from 'std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...) [with _Alloc = std::allocator<g3::internal::Sink<g3::FileSink> >; _Args = {std::unique_ptr<g3::FileSink, std::default_delete<g3::FileSink> >, void (g3::FileSink::*&)(g3::MoveOnCopy<g3::LogMessage>)}; _Tp = g3::internal::Sink<g3::FileSink>; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]'
/usr/include/c++/4.7.2/bits/shared_ptr.h:317:64:   required from 'std::shared_ptr<_Tp>::shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...) [with _Alloc = std::allocator<g3::internal::Sink<g3::FileSink> >; _Args = {std::unique_ptr<g3::FileSink, std::default_delete<g3::FileSink> >, void (g3::FileSink::*&)(g3::MoveOnCopy<g3::LogMessage>)}; _Tp = g3::internal::Sink<g3::FileSink>]'
/usr/include/c++/4.7.2/bits/shared_ptr.h:599:39:   required from 'std::shared_ptr<_Tp> std::allocate_shared(const _Alloc&, _Args&& ...) [with _Tp = g3::internal::Sink<g3::FileSink>; _Alloc = std::allocator<g3::internal::Sink<g3::FileSink> >; _Args = {std::unique_ptr<g3::FileSink, std::default_delete<g3::FileSink> >, void (g3::FileSink::*&)(g3::MoveOnCopy<g3::LogMessage>)}]'
/usr/include/c++/4.7.2/bits/shared_ptr.h:615:42:   required from 'std::shared_ptr<_Tp1> std::make_shared(_Args&& ...) [with _Tp = g3::internal::Sink<g3::FileSink>; _Args = {std::unique_ptr<g3::FileSink, std::default_delete<g3::FileSink> >, void (g3::FileSink::*&)(g3::MoveOnCopy<g3::LogMessage>)}]'
E:\Sources\Packages\g3log-1.2\g3log\src\g3log/logworker.hpp:99:75:   required from 'std::unique_ptr<g3::SinkHandle<T> > g3::LogWorker::addSink(std::unique_ptr<T>, DefaultLogCall) [with T = g3::FileSink; DefaultLogCall = void (g3::FileSink::*)(g3::MoveOnCopy<g3::LogMessage>)]'
E:\Sources\Packages\g3log-1.2\g3log\src\logworker.cpp:124:114:   required from here
E:\Sources\Packages\g3log-1.2\g3log\src/g3log/sink.hpp:48:84: error: cannot allocate an object of abstract type 'g3::internal::SinkWrapper'
In file included from E:\Sources\Packages\g3log-1.2\g3log\src\g3log/logworker.hpp:15:0,
                 from E:\Sources\Packages\g3log-1.2\g3log\src\logworker.cpp:9:
E:\Sources\Packages\g3log-1.2\g3log\src/g3log/sinkwrapper.hpp:16:14: note:   because the following virtual functions are pure within 'g3::internal::SinkWrapper':
E:\Sources\Packages\g3log-1.2\g3log\src/g3log/sinkwrapper.hpp:18:23: note:      virtual void g3::internal::SinkWrapper::send(g3::LogMessageMover)
make[2]: *** [CMakeFiles/g3logger.dir/src/logworker.cpp.o] Error 1
make[1]: *** [CMakeFiles/g3logger.dir/all] Error 2
make: *** [all] Error 2

**Comment by KjellKod** [comment]
please pull latest from masters so the travis build works

**Comment by KjellKod** [comment]
Would this work?

```
 template<typename DefaultLogCall >
         Sink(std::unique_ptr<T> sink, DefaultLogCall call)
            : SinkWrapper(), // not using brace initialization
         _real_sink {std::move(sink)},
         _bg(kjellkod::Active::createActive()),
         _default_log_call(std::bind(call, _real_sink.get(), std::placeholders::_1)) {
         }
```

Not calling the base class constructor I think is a bad idea. Frankly I'm a bit compiler rusty but I think that can have consequences for the virtual destruction calls if it is not instantiated.

**Comment by KjellKod** [comment]
:+1: good to go once formatting is fixed

**Pull request merged**
