### PR TITLE
Add in support for configurable kMaxMessageValue #203

### PR DESCRIPTION
**Pull request by mobileben**
Sorry for the delay in updating this. Hopefully this does it. Compile time option for this (default is the current static). Using ```std::vector<char>```.

### CODE REVIEW

**Comment by KjellKod** [comment]
👍  @mobileben can you update the API document for this new function?  Ref: https://github.com/KjellKod/g3log/blob/master/API.markdown

Once that is done then this is ready to be merged!

Thanks for a great PR

**Comment by KjellKod** [comment]
I'm going to go ahead and merge this. I realize that there is no unit tests or examples that verify this currently

**Comment by mobileben** [comment]
@KjellKod did this not make it in? I was updating the code and noticed that I can no longer compile against my code base since it was dependent on this.

**Comment by KjellKod** [comment]
Oops. My bad

**Comment by KjellKod** [comment]
@mobilben it is merged now. Sorry for the hiccup

**Comment by mobileben** [comment]
Cool, thanks! I'm looking at the CI right now. I'm pretty sure CircleCI is a paid service when it comes to iOS, I've sent them a question. I'm looking at Travis CI. There is some wonkiness with the tests in that we will probably have to build them in Xcode, which means that cmake (Unless I suppose we try and generate an Xcode file from it) can't be used to build them. I'm looking at this project right now for integrating gtest with Xcode. https://github.com/mattstevens/xcode-googletest.

The thought is to use that Xcode project as the basis for the tests.

**Comment by mobileben** [comment]
Oh, I did merge and things are working. I ended up fixing a problem in the iOS cmake file and updated my branch for the iOS build.

**Pull request merged**
